#!/usr/bin/env bash
set -euo pipefail

selected_name="$1"

# Aguarda a troca de sessão
sleep 0.2

for s in $(tmux list-sessions -F '#S'); do
  if [[ "$s" != "$selected_name" ]]; then
    tmux kill-session -t "$s" 2>/dev/null || true
  fi
done
